title: Anshul Kumar

# logo: 
description: Vaughan, Ontario | anshul1013@gmail.com | [LinkedIn](https://www.linkedin.com/in/anshul-kumar-96570713a) | Phone: 647 534 4313 

# show_downloads: True
theme: jekyll-theme-cayman

