# title: Anshul Kumar

# # logo: 
# description:  
# # show_downloads: True
# theme: jekyll-theme-cayman


title: Anshul Kumar

description: Vaughan, Ontario | anshul1013@gmail.com | [LinkedIn](Your_LinkedIn_Profile_Link) | Phone: 647 534 4313 

remote_theme: pages-themes/cayman@v0.2.0
plugins: - jekyll-remote-theme 
theme: jekyll-theme-cayman
